@hostname = http://localhost:3000
@market = ETH

###
# @name Place an order
POST {{hostname}}/order
Content-Type: application/json

{
    "bid": false,
    "size": 2,
    "type": "MARKET",
    "market": "{{market}}"
}

###
# @name getOrderbook
GET {{hostname}}/book/{{market}}

###
# @name cancelOrder
DELETE {{hostname}}/order/{{getOrderbook.response.body.Bids[0].ID}}

###
